name: Deploy to Linode

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.LINODE_IP }}
          port: ${{ secrets.LINODE_PORT }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            cd apps/portfolio-page/
            git pull origin master
            docker compose down --volumes
            docker system prune -af --volumes
            docker compose build --no-cache
            docker compose up -d
