name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Linode
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.LINODE_IP }}
        username: ${{ secrets.LINODE_USER }}
        key: ${{ secrets.LINODE_SSH_KEY }}
        script: |
          cd /path/to/project
          git pull origin main
          docker-compose down
          docker-compose up --build -d
